### ISSUE TITLE
Where does the thrower cable run?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-twelve#22]
I can not see where it is running.

![image](https://user-images.githubusercontent.com/5435954/205357254-19f24b01-6a67-4b19-9ee6-9bede686bb6a.png)

**Comment by Akustav** [comment]
Does it also line up with where the cable comes out of the motor? There is no indication

**Comment by kennolot** [comment]
Well I couldn't find the exact same motor file or image for reference so I can't really add the indication into the design. But since I used the same idea for the test robot thrower then I can assume this works too. And in an unlikely situation when it doesn't I can always cut out the hole manually.

**Comment by Akustav** [comment]
You can modify the model yourself. You have the motor available so I see no problem in measuring and adding the wire outlet area so it is hilighted

**Comment by Akustav** [comment]
This does not look equivalent to me. The current representation gives a false sense of cable run and can hinder the ball.

![image](https://user-images.githubusercontent.com/5435954/207174588-0db664be-b2a8-47cb-a47a-1643e13c7fd7.png)

![image](https://user-images.githubusercontent.com/5435954/207174848-aad23997-b5f4-4b42-a6e7-af90a10d2f41.png)

You'd rather want the cables to run here:
![image](https://user-images.githubusercontent.com/5435954/207174978-b676ee44-88bb-463a-a5c4-e09d0cfebfa1.png)
